version: '3.8'

services:
  solr:
    image: solr:latest
    container_name: my_solr
    ports:
      - "8983:8983"
    environment:
      - SOLR_CORE=mycore
    volumes:
      - solr_data:/var/solr/data

volumes:
  solr_data:
